// @ts-nocheck — auto-generated by `drizzle-kit pull`. Mutual FKs between
// tables (e.g. jobTitles ↔ appUsers, schedulingBookings ↔ clientPackageSessions)
// trip TS's circular type inference. Re-pulling regenerates this file; we
// don't hand-edit it. Runtime types still flow correctly into queries.
import { pgTable, unique, pgPolicy, check, uuid, text, jsonb, timestamp, index, integer, boolean, foreignKey, date, time, type AnyPgColumn, numeric, serial, uniqueIndex, bigint, primaryKey } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const withinStaff = pgTable("within_staff", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	firstName: text("first_name").notNull(),
	lastName: text("last_name").notNull(),
	email: text().notNull(),
	role: text().default('staff').notNull(),
	title: text(),
	permissions: jsonb().default({}),
	status: text().default('active').notNull(),
	addedBy: text("added_by"),
	lastLoginAt: timestamp("last_login_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	unique("within_staff_email_key").on(table.email),
	pgPolicy("Anon can read active staff emails", { as: "permissive", for: "select", to: ["anon"], using: sql`(status = 'active'::text)` }),
	pgPolicy("within_staff_authorized", { as: "permissive", for: "all", to: ["authenticated"] }),
	check("within_staff_role_check", sql`role = ANY (ARRAY['admin'::text, 'provider'::text, 'staff'::text, 'readonly'::text])`),
	check("within_staff_status_check", sql`status = ANY (ARRAY['active'::text, 'inactive'::text])`),
]);

export const withinAuditLog = pgTable("within_audit_log", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userEmail: text("user_email").notNull(),
	action: text().notNull(),
	resourceType: text("resource_type").notNull(),
	details: text(),
	ipHint: text("ip_hint"),
	timestamp: timestamp({ withTimezone: true, mode: 'string' }).defaultNow(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_within_audit_log_action").using("btree", table.action.asc().nullsLast().op("timestamptz_ops"), table.timestamp.desc().nullsFirst().op("text_ops")),
	index("idx_within_audit_log_user_time").using("btree", table.userEmail.asc().nullsLast().op("timestamptz_ops"), table.timestamp.desc().nullsFirst().op("timestamptz_ops")),
	pgPolicy("Anon can insert audit logs", { as: "permissive", for: "insert", to: ["anon"], withCheck: sql`true`  }),
	pgPolicy("Authenticated users can insert audit logs", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("Authenticated users can read audit logs", { as: "permissive", for: "select", to: ["authenticated"] }),
]);

export const imageLibrary = pgTable("image_library", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	prompt: text().notNull(),
	revisedPrompt: text("revised_prompt"),
	style: text(),
	aspectRatio: text("aspect_ratio"),
	model: text().default('gemini-2.5-flash-image'),
	publicUrl: text("public_url").notNull(),
	storagePath: text("storage_path").notNull(),
	width: integer(),
	height: integer(),
	tags: text().array().default([""]),
	createdBy: text("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("image_library_created_at_idx").using("btree", table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	index("image_library_tags_idx").using("gin", table.tags.asc().nullsLast().op("array_ops")),
	pgPolicy("image_library_delete", { as: "permissive", for: "delete", to: ["public"], using: sql`is_within_authorized()` }),
	pgPolicy("image_library_insert", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("image_library_read", { as: "permissive", for: "select", to: ["public"] }),
	pgPolicy("image_library_update", { as: "permissive", for: "update", to: ["public"] }),
]);

export const wcServices = pgTable("wc_services", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	slug: text().notNull(),
	name: text().notNull(),
	tagline: text(),
	description: text(),
	priceCents: integer("price_cents"),
	priceDisplay: text("price_display"),
	duration: text(),
	category: text().default('outpatient'),
	features: jsonb().default([]),
	sortOrder: integer("sort_order").default(0),
	isActive: boolean("is_active").default(true),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	unique("wc_services_slug_key").on(table.slug),
	pgPolicy("Authenticated manage services", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("Public can view active services", { as: "permissive", for: "select", to: ["public"] }),
	check("wc_services_category_check", sql`category = ANY (ARRAY['outpatient'::text, 'retreat'::text])`),
]);

export const wcTeamMembers = pgTable("wc_team_members", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	role: text(),
	bio: text(),
	photoUrl: text("photo_url"),
	isActive: boolean("is_active").default(true),
	sortOrder: integer("sort_order").default(0),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	pgPolicy("Authenticated manage team", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("Public can view active team members", { as: "permissive", for: "select", to: ["public"] }),
]);

export const wcPosts = pgTable("wc_posts", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	slug: text().notNull(),
	title: text().notNull(),
	excerpt: text(),
	content: text(),
	author: text(),
	category: text(),
	tags: text().array(),
	featuredImageUrl: text("featured_image_url"),
	publishedAt: timestamp("published_at", { withTimezone: true, mode: 'string' }),
	isPublished: boolean("is_published").default(false),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_wc_posts_published").using("btree", table.isPublished.asc().nullsLast().op("bool_ops"), table.publishedAt.desc().nullsFirst().op("timestamptz_ops")),
	index("idx_wc_posts_slug").using("btree", table.slug.asc().nullsLast().op("text_ops")),
	unique("wc_posts_slug_key").on(table.slug),
	pgPolicy("Authenticated manage posts", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("Public can view published posts", { as: "permissive", for: "select", to: ["public"] }),
]);

export const wcBookings = pgTable("wc_bookings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	serviceId: text("service_id"),
	serviceName: text("service_name").notNull(),
	providerId: uuid("provider_id"),
	bookingDate: date("booking_date").notNull(),
	bookingTime: text("booking_time").notNull(),
	clientFirstName: text("client_first_name").notNull(),
	clientLastName: text("client_last_name").notNull(),
	clientEmail: text("client_email").notNull(),
	clientPhone: text("client_phone"),
	clientCity: text("client_city"),
	clientState: text("client_state"),
	comments: text(),
	amount: integer(),
	status: text().default('pending'),
	paymentStatus: text("payment_status").default('unpaid'),
	paymentId: text("payment_id"),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_wc_bookings_date").using("btree", table.bookingDate.asc().nullsLast().op("date_ops")),
	index("idx_wc_bookings_email").using("btree", table.clientEmail.asc().nullsLast().op("text_ops")),
	index("idx_wc_bookings_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.providerId],
			foreignColumns: [wcProviders.id],
			name: "wc_bookings_provider_id_fkey"
		}),
	pgPolicy("Authenticated manage bookings", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("Public can create bookings", { as: "permissive", for: "insert", to: ["public"] }),
	check("wc_bookings_payment_status_check", sql`payment_status = ANY (ARRAY['unpaid'::text, 'deposit_paid'::text, 'paid'::text, 'refunded'::text])`),
	check("wc_bookings_status_check", sql`status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text, 'completed'::text, 'no_show'::text])`),
]);

export const wcContactSubmissions = pgTable("wc_contact_submissions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	firstName: text("first_name").notNull(),
	lastName: text("last_name").notNull(),
	email: text().notNull(),
	phone: text(),
	city: text(),
	state: text(),
	message: text(),
	source: text().default('contact_form'),
	status: text().default('new'),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_wc_contact_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	pgPolicy("Authenticated manage contacts", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("Public can submit contact forms", { as: "permissive", for: "insert", to: ["public"] }),
	check("wc_contact_submissions_status_check", sql`status = ANY (ARRAY['new'::text, 'contacted'::text, 'resolved'::text])`),
]);

export const wcNewsletterSubscribers = pgTable("wc_newsletter_subscribers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	email: text().notNull(),
	subscribedAt: timestamp("subscribed_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	isActive: boolean("is_active").default(true),
}, (table) => [
	unique("wc_newsletter_subscribers_email_key").on(table.email),
	pgPolicy("Authenticated manage newsletter", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("Public can subscribe to newsletter", { as: "permissive", for: "insert", to: ["public"] }),
]);

export const wcProviders = pgTable("wc_providers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	role: text(),
	bio: text(),
	photoUrl: text("photo_url"),
	isActive: boolean("is_active").default(true),
	sortOrder: integer("sort_order").default(0),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	pgPolicy("Authenticated manage providers", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("Public can view active providers", { as: "permissive", for: "select", to: ["public"] }),
]);

export const wcProviderSchedules = pgTable("wc_provider_schedules", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	providerId: uuid("provider_id"),
	dayOfWeek: integer("day_of_week").notNull(),
	startTime: time("start_time").notNull(),
	endTime: time("end_time").notNull(),
	isActive: boolean("is_active").default(true),
}, (table) => [
	foreignKey({
			columns: [table.providerId],
			foreignColumns: [wcProviders.id],
			name: "wc_provider_schedules_provider_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Authenticated manage schedules", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("Public can view active schedules", { as: "permissive", for: "select", to: ["public"] }),
	check("wc_provider_schedules_day_of_week_check", sql`(day_of_week >= 0) AND (day_of_week <= 6)`),
]);

export const appUsers = pgTable("app_users", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	authUserId: uuid("auth_user_id"),
	email: text().notNull(),
	role: text().default('public').notNull(),
	displayName: text("display_name"),
	firstName: text("first_name"),
	lastName: text("last_name"),
	phone: text(),
	avatarUrl: text("avatar_url"),
	personId: integer("person_id"),
	isCurrentResident: boolean("is_current_resident").default(false),
	invitedBy: uuid("invited_by"),
	lastLoginAt: timestamp("last_login_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	isArchived: boolean("is_archived").default(false).notNull(),
	archivedAt: timestamp("archived_at", { withTimezone: true, mode: 'string' }),
	archivedBy: uuid("archived_by"),
	jobTitleId: uuid("job_title_id"),
	canSchedule: boolean("can_schedule").default(false).notNull(),
}, (table) => [
	index("idx_app_users_is_archived").using("btree", table.isArchived.asc().nullsLast().op("bool_ops")).where(sql`(is_archived = false)`),
	index("idx_app_users_job_title_id").using("btree", table.jobTitleId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.archivedBy],
			foreignColumns: [table.id],
			name: "app_users_archived_by_fkey"
		}),
	// FK to auth.users.id — exists in DB but not modeled in Drizzle since
	// pull only introspects `public`. Re-add when we explicitly model
	// auth.users for cross-schema joins.
	// foreignKey({
	// 		columns: [table.authUserId],
	// 		foreignColumns: [users.id],
	// 		name: "app_users_auth_user_id_fkey"
	// 	}).onDelete("cascade"),
	foreignKey({
			columns: [table.jobTitleId],
			foreignColumns: [jobTitles.id],
			name: "app_users_job_title_fk"
		}).onDelete("set null"),
	unique("app_users_auth_user_id_key").on(table.authUserId),
	pgPolicy("Users can insert own record", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(auth.uid() = auth_user_id)`  }),
	pgPolicy("Users can read own record", { as: "permissive", for: "select", to: ["public"] }),
	pgPolicy("Users can update own record", { as: "permissive", for: "update", to: ["public"] }),
	check("app_users_role_check", sql`role = ANY (ARRAY['oracle'::text, 'admin'::text, 'staff'::text, 'resident'::text, 'associate'::text, 'demo'::text, 'public'::text, 'prospect'::text])`),
]);

export const userInvitations = pgTable("user_invitations", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	email: text().notNull(),
	role: text().default('public').notNull(),
	status: text().default('pending').notNull(),
	invitedBy: uuid("invited_by"),
	invitedAt: timestamp("invited_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	expiresAt: timestamp("expires_at", { withTimezone: true, mode: 'string' }).default(sql`(now() + '90 days'::interval)`),
	emailSentAt: timestamp("email_sent_at", { withTimezone: true, mode: 'string' }),
	emailSendCount: integer("email_send_count").default(0).notNull(),
}, (table) => [
	index("idx_user_invitations_email_sent_at").using("btree", table.emailSentAt.asc().nullsLast().op("timestamptz_ops")),
	pgPolicy("Admins can insert invitations", { as: "permissive", for: "insert", to: ["authenticated"], withCheck: sql`(invited_by IN ( SELECT app_users.id
   FROM app_users
  WHERE ((app_users.auth_user_id = auth.uid()) AND (app_users.role = ANY (ARRAY['admin'::text, 'oracle'::text])))))`  }),
	pgPolicy("Authenticated can read invitations", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Authenticated can update invitations", { as: "permissive", for: "update", to: ["authenticated"] }),
	check("user_invitations_role_check", sql`role = ANY (ARRAY['oracle'::text, 'admin'::text, 'staff'::text, 'resident'::text, 'associate'::text, 'demo'::text, 'public'::text, 'prospect'::text])`),
	check("user_invitations_status_check", sql`status = ANY (ARRAY['pending'::text, 'accepted'::text, 'expired'::text])`),
]);

export const stripeConfig = pgTable("stripe_config", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	testMode: boolean("test_mode").default(true).notNull(),
	secretKey: text("secret_key").notNull(),
	publishableKey: text("publishable_key"),
	webhookSecret: text("webhook_secret"),
	isActive: boolean("is_active").default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("one_active_per_mode").on(table.testMode, table.isActive),
]);

export const todoCategories = pgTable("todo_categories", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	title: text().notNull(),
	iconSvg: text("icon_svg"),
	displayOrder: integer("display_order").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	pgPolicy("Anon can delete todo_categories", { as: "permissive", for: "delete", to: ["anon"], using: sql`true` }),
	pgPolicy("Anon can insert todo_categories", { as: "permissive", for: "insert", to: ["anon"] }),
	pgPolicy("Anon can read todo_categories", { as: "permissive", for: "select", to: ["anon"] }),
	pgPolicy("Anon can update todo_categories", { as: "permissive", for: "update", to: ["anon"] }),
	pgPolicy("Authenticated users can delete todo_categories", { as: "permissive", for: "delete", to: ["authenticated"] }),
	pgPolicy("Authenticated users can insert todo_categories", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("Authenticated users can read todo_categories", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Authenticated users can update todo_categories", { as: "permissive", for: "update", to: ["authenticated"] }),
]);

export const todoItems = pgTable("todo_items", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	categoryId: uuid("category_id"),
	title: text().notNull(),
	description: text(),
	badge: text(),
	isChecked: boolean("is_checked").default(false),
	checkedBy: uuid("checked_by"),
	checkedAt: timestamp("checked_at", { withTimezone: true, mode: 'string' }),
	displayOrder: integer("display_order").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	foreignKey({
			columns: [table.categoryId],
			foreignColumns: [todoCategories.id],
			name: "todo_items_category_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Anon can delete todo_items", { as: "permissive", for: "delete", to: ["anon"], using: sql`true` }),
	pgPolicy("Anon can insert todo_items", { as: "permissive", for: "insert", to: ["anon"] }),
	pgPolicy("Anon can read todo_items", { as: "permissive", for: "select", to: ["anon"] }),
	pgPolicy("Anon can update todo_items", { as: "permissive", for: "update", to: ["anon"] }),
	pgPolicy("Authenticated users can delete todo_items", { as: "permissive", for: "delete", to: ["authenticated"] }),
	pgPolicy("Authenticated users can insert todo_items", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("Authenticated users can read todo_items", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Authenticated users can update todo_items", { as: "permissive", for: "update", to: ["authenticated"] }),
]);

export const spaces = pgTable("spaces", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	slug: text(),
	description: text(),
	location: text(),
	type: text(),
	parentId: uuid("parent_id"),
	monthlyRate: integer("monthly_rate"),
	weeklyRate: integer("weekly_rate"),
	nightlyRate: integer("nightly_rate"),
	rentalTerm: text("rental_term"),
	standardDeposit: text("standard_deposit"),
	sqFootage: integer("sq_footage"),
	minResidents: integer("min_residents").default(1),
	maxResidents: integer("max_residents"),
	bedsKing: integer("beds_king").default(0),
	bedsQueen: integer("beds_queen").default(0),
	bedsDouble: integer("beds_double").default(0),
	bedsTwin: integer("beds_twin").default(0),
	bedsFolding: integer("beds_folding").default(0),
	bathPrivacy: text("bath_privacy"),
	bathFixture: text("bath_fixture"),
	genderRestriction: text("gender_restriction").default('none'),
	isListed: boolean("is_listed").default(false),
	isSecret: boolean("is_secret").default(false),
	isMicro: boolean("is_micro").default(false),
	canBeDwelling: boolean("can_be_dwelling").default(false),
	canBeEvent: boolean("can_be_event").default(false),
	isArchived: boolean("is_archived").default(false),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	minNights: integer("min_nights").default(1),
	bookingCategory: text("booking_category"),
	bookingName: text("booking_name"),
	hourlyRate: numeric("hourly_rate", { precision: 10, scale:  2 }),
	overnightRate: numeric("overnight_rate", { precision: 10, scale:  2 }),
	fullDayRate: numeric("full_day_rate", { precision: 10, scale:  2 }),
	cleaningFee: numeric("cleaning_fee", { precision: 10, scale:  2 }).default('0'),
	minHours: integer("min_hours").default(2),
	staffOnly: boolean("staff_only").default(false),
	bookingDisplayOrder: integer("booking_display_order").default(0),
	spaceType: text("space_type"),
	floor: text(),
	hasPrivateBath: boolean("has_private_bath"),
	features: jsonb().default({}).notNull(),
}, (table) => [
	foreignKey({
			columns: [table.parentId],
			foreignColumns: [table.id],
			name: "spaces_parent_id_fkey"
		}).onDelete("set null"),
	pgPolicy("spaces_auth_delete", { as: "permissive", for: "delete", to: ["authenticated"], using: sql`true` }),
	pgPolicy("spaces_auth_insert", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("spaces_auth_read", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("spaces_auth_update", { as: "permissive", for: "update", to: ["authenticated"] }),
	pgPolicy("spaces_public_read", { as: "permissive", for: "select", to: ["public"] }),
	check("spaces_booking_category_check", sql`booking_category = ANY (ARRAY['house_room'::text, 'rental_space'::text, 'wellness_room'::text])`),
	check("spaces_floor_check", sql`floor = ANY (ARRAY['downstairs'::text, 'upstairs'::text])`),
	check("spaces_space_type_check", sql`space_type = ANY (ARRAY['session'::text, 'lodging'::text, 'both'::text])`),
]);

export const investorAccess = pgTable("investor_access", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	email: text().notNull(),
	role: text().default('admin').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("investor_access_email_key").on(table.email),
	pgPolicy("Service role full access", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.role() = 'service_role'::text)` }),
	pgPolicy("Users can read own access", { as: "permissive", for: "select", to: ["public"] }),
]);

export const propertyConfig = pgTable("property_config", {
	id: integer().default(1).primaryKey().notNull(),
	config: jsonb().default({}).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	pgPolicy("Anon can read property_config", { as: "permissive", for: "select", to: ["anon"], using: sql`true` }),
	pgPolicy("Authenticated users can read property_config", { as: "permissive", for: "select", to: ["authenticated"] }),
	check("single_row", sql`id = 1`),
]);

export const bookingRooms = pgTable("booking_rooms", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	spaceId: uuid("space_id").notNull(),
	appUserId: uuid("app_user_id"),
	guestName: text("guest_name"),
	guestEmail: text("guest_email"),
	guestPhone: text("guest_phone"),
	checkIn: date("check_in").notNull(),
	checkOut: date("check_out").notNull(),
	nightlyRate: numeric("nightly_rate", { precision: 10, scale:  2 }).notNull(),
	totalAmount: numeric("total_amount", { precision: 10, scale:  2 }).notNull(),
	status: text().default('confirmed').notNull(),
	source: text().default('direct'),
	notes: text(),
	createdBy: uuid("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_booking_rooms_dates").using("btree", table.checkIn.asc().nullsLast().op("date_ops"), table.checkOut.asc().nullsLast().op("date_ops")),
	index("idx_booking_rooms_space").using("btree", table.spaceId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.appUserId],
			foreignColumns: [appUsers.id],
			name: "booking_rooms_app_user_id_fkey"
		}),
	foreignKey({
			columns: [table.spaceId],
			foreignColumns: [spaces.id],
			name: "booking_rooms_space_id_fkey"
		}),
	pgPolicy("auth_delete_booking_rooms", { as: "permissive", for: "delete", to: ["authenticated"], using: sql`true` }),
	pgPolicy("auth_insert_booking_rooms", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("auth_read_booking_rooms", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("auth_update_booking_rooms", { as: "permissive", for: "update", to: ["authenticated"] }),
	check("booking_rooms_source_check", sql`source = ANY (ARRAY['direct'::text, 'airbnb'::text, 'vrbo'::text, 'phone'::text, 'walk_in'::text, 'online'::text])`),
	check("booking_rooms_status_check", sql`status = ANY (ARRAY['hold'::text, 'confirmed'::text, 'checked_in'::text, 'checked_out'::text, 'cancelled'::text, 'no_show'::text])`),
	check("min_2_nights", sql`(check_out - check_in) >= 2`),
]);

export const bookingSpaces = pgTable("booking_spaces", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	spaceId: uuid("space_id").notNull(),
	appUserId: uuid("app_user_id"),
	clientName: text("client_name"),
	clientEmail: text("client_email"),
	clientPhone: text("client_phone"),
	bookingType: text("booking_type").notNull(),
	startDatetime: timestamp("start_datetime", { withTimezone: true, mode: 'string' }).notNull(),
	endDatetime: timestamp("end_datetime", { withTimezone: true, mode: 'string' }).notNull(),
	hourlyRate: numeric("hourly_rate", { precision: 10, scale:  2 }),
	flatRate: numeric("flat_rate", { precision: 10, scale:  2 }),
	cleaningFee: numeric("cleaning_fee", { precision: 10, scale:  2 }).default('0'),
	totalAmount: numeric("total_amount", { precision: 10, scale:  2 }).notNull(),
	status: text().default('confirmed').notNull(),
	notes: text(),
	createdBy: uuid("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_booking_spaces_dates").using("btree", table.startDatetime.asc().nullsLast().op("timestamptz_ops"), table.endDatetime.asc().nullsLast().op("timestamptz_ops")),
	index("idx_booking_spaces_space").using("btree", table.spaceId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.appUserId],
			foreignColumns: [appUsers.id],
			name: "booking_spaces_app_user_id_fkey"
		}),
	foreignKey({
			columns: [table.spaceId],
			foreignColumns: [spaces.id],
			name: "booking_spaces_space_id_fkey"
		}),
	pgPolicy("auth_delete_booking_spaces", { as: "permissive", for: "delete", to: ["authenticated"], using: sql`true` }),
	pgPolicy("auth_insert_booking_spaces", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("auth_read_booking_spaces", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("auth_update_booking_spaces", { as: "permissive", for: "update", to: ["authenticated"] }),
	check("booking_spaces_booking_type_check", sql`booking_type = ANY (ARRAY['hourly'::text, 'full_day'::text, 'overnight'::text])`),
	check("booking_spaces_status_check", sql`status = ANY (ARRAY['hold'::text, 'confirmed'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])`),
]);

export const staffMembers = pgTable("staff_members", {
	id: serial().primaryKey().notNull(),
	appUserId: uuid("app_user_id"),
	displayName: text("display_name").notNull(),
	color: text().notNull(),
	isActive: boolean("is_active").default(true),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	foreignKey({
			columns: [table.appUserId],
			foreignColumns: [appUsers.id],
			name: "staff_members_app_user_id_fkey"
		}),
	pgPolicy("auth_insert_staff_members", { as: "permissive", for: "insert", to: ["authenticated"], withCheck: sql`true`  }),
	pgPolicy("auth_read_staff_members", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("auth_update_staff_members", { as: "permissive", for: "update", to: ["authenticated"] }),
]);

export const activityTypes = pgTable("activity_types", {
	id: serial().primaryKey().notNull(),
	name: text().notNull(),
	defaultDurationMin: integer("default_duration_min").default(60).notNull(),
	bufferMin: integer("buffer_min").default(30).notNull(),
	color: text().notNull(),
	defaultSpaceId: uuid("default_space_id"),
	price: numeric({ precision: 10, scale:  2 }),
	isActive: boolean("is_active").default(true),
	displayOrder: integer("display_order").default(0),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	foreignKey({
			columns: [table.defaultSpaceId],
			foreignColumns: [spaces.id],
			name: "activity_types_default_space_id_fkey"
		}),
	unique("activity_types_name_key").on(table.name),
	pgPolicy("auth_insert_activity_types", { as: "permissive", for: "insert", to: ["authenticated"], withCheck: sql`true`  }),
	pgPolicy("auth_read_activity_types", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("auth_update_activity_types", { as: "permissive", for: "update", to: ["authenticated"] }),
]);

export const activityBookings = pgTable("activity_bookings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	activityTypeId: integer("activity_type_id").notNull(),
	staffMemberId: integer("staff_member_id").notNull(),
	spaceId: uuid("space_id").notNull(),
	appUserId: uuid("app_user_id"),
	clientName: text("client_name"),
	startDatetime: timestamp("start_datetime", { withTimezone: true, mode: 'string' }).notNull(),
	endDatetime: timestamp("end_datetime", { withTimezone: true, mode: 'string' }).notNull(),
	bufferEnd: timestamp("buffer_end", { withTimezone: true, mode: 'string' }).notNull(),
	price: numeric({ precision: 10, scale:  2 }),
	status: text().default('scheduled').notNull(),
	notes: text(),
	createdBy: uuid("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_activity_bookings_dates").using("btree", table.startDatetime.asc().nullsLast().op("timestamptz_ops"), table.endDatetime.asc().nullsLast().op("timestamptz_ops")),
	index("idx_activity_bookings_space").using("btree", table.spaceId.asc().nullsLast().op("uuid_ops")),
	index("idx_activity_bookings_staff").using("btree", table.staffMemberId.asc().nullsLast().op("int4_ops")),
	foreignKey({
			columns: [table.activityTypeId],
			foreignColumns: [activityTypes.id],
			name: "activity_bookings_activity_type_id_fkey"
		}),
	foreignKey({
			columns: [table.appUserId],
			foreignColumns: [appUsers.id],
			name: "activity_bookings_app_user_id_fkey"
		}),
	foreignKey({
			columns: [table.spaceId],
			foreignColumns: [spaces.id],
			name: "activity_bookings_space_id_fkey"
		}),
	foreignKey({
			columns: [table.staffMemberId],
			foreignColumns: [staffMembers.id],
			name: "activity_bookings_staff_member_id_fkey"
		}),
	pgPolicy("auth_delete_activity_bookings", { as: "permissive", for: "delete", to: ["authenticated"], using: sql`true` }),
	pgPolicy("auth_insert_activity_bookings", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("auth_read_activity_bookings", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("auth_update_activity_bookings", { as: "permissive", for: "update", to: ["authenticated"] }),
	check("activity_bookings_status_check", sql`status = ANY (ARRAY['scheduled'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text, 'no_show'::text])`),
]);

export const membershipPlans = pgTable("membership_plans", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	description: text(),
	billingCycle: text("billing_cycle").default('monthly').notNull(),
	price: numeric({ precision: 10, scale:  2 }).notNull(),
	benefits: jsonb().default([]),
	restrictions: jsonb().default({}),
	isActive: boolean("is_active").default(true),
	sortOrder: integer("sort_order").default(0),
	color: text().default('#d4883a'),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	pgPolicy("Authenticated read membership_plans", { as: "permissive", for: "select", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Authenticated write membership_plans", { as: "permissive", for: "all", to: ["authenticated"] }),
	check("membership_plans_billing_cycle_check", sql`billing_cycle = ANY (ARRAY['monthly'::text, 'annual'::text, 'one_time'::text])`),
]);

export const memberMemberships = pgTable("member_memberships", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	appUserId: uuid("app_user_id"),
	planId: uuid("plan_id"),
	status: text().default('active').notNull(),
	memberName: text("member_name").notNull(),
	memberEmail: text("member_email"),
	memberPhone: text("member_phone"),
	startDate: date("start_date").default(sql`CURRENT_DATE`).notNull(),
	endDate: date("end_date"),
	nextBillingDate: date("next_billing_date"),
	paymentMethod: text("payment_method"),
	amountPaid: numeric("amount_paid", { precision: 10, scale:  2 }).default('0'),
	totalVisits: integer("total_visits").default(0),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	foreignKey({
			columns: [table.appUserId],
			foreignColumns: [appUsers.id],
			name: "member_memberships_app_user_id_fkey"
		}),
	foreignKey({
			columns: [table.planId],
			foreignColumns: [membershipPlans.id],
			name: "member_memberships_plan_id_fkey"
		}),
	pgPolicy("Authenticated read member_memberships", { as: "permissive", for: "select", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Authenticated write member_memberships", { as: "permissive", for: "all", to: ["authenticated"] }),
	check("member_memberships_status_check", sql`status = ANY (ARRAY['active'::text, 'paused'::text, 'expired'::text, 'cancelled'::text, 'past_due'::text, 'trial'::text])`),
]);

export const crmLeadSources = pgTable("crm_lead_sources", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	slug: text().notNull(),
	isActive: boolean("is_active").default(true),
	sortOrder: integer("sort_order").default(0),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	unique("crm_lead_sources_slug_key").on(table.slug),
	pgPolicy("Authenticated users can read CRM lookups", { as: "permissive", for: "select", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Service role full access lead_sources", { as: "permissive", for: "all", to: ["service_role"] }),
]);

export const crmPipelineStages = pgTable("crm_pipeline_stages", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	businessLine: text("business_line").notNull(),
	name: text().notNull(),
	slug: text().notNull(),
	sortOrder: integer("sort_order").notNull(),
	color: text().default('#6B7280'),
	isTerminal: boolean("is_terminal").default(false),
	autoAdvanceOn: text("auto_advance_on"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	unique("crm_pipeline_stages_business_line_slug_key").on(table.businessLine, table.slug),
	pgPolicy("Authenticated users can read CRM stages", { as: "permissive", for: "select", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Service role full access stages", { as: "permissive", for: "all", to: ["service_role"] }),
]);

export const withinNotes = pgTable("within_notes", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	patientId: uuid("patient_id"),
	noteDate: date("note_date"),
	noteType: text("note_type").default('soap'),
	provider: text(),
	subjective: text(),
	objective: text(),
	assessment: text(),
	plan: text(),
	status: text().default('draft'),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	scribeTranscript: text("scribe_transcript"),
	scribeExtracts: jsonb("scribe_extracts"),
	noteFormat: text("note_format").default('SOAP'),
}, (table) => [
	foreignKey({
			columns: [table.patientId],
			foreignColumns: [withinPatients.id],
			name: "within_notes_patient_id_fkey"
		}),
	pgPolicy("within_notes_authorized", { as: "permissive", for: "all", to: ["authenticated"], using: sql`is_within_authorized()`, withCheck: sql`is_within_authorized()`  }),
]);

export const withinPatients = pgTable("within_patients", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	firstName: text("first_name").notNull(),
	lastName: text("last_name").notNull(),
	dob: date(),
	sex: text(),
	genderIdentity: text("gender_identity"),
	pronouns: text(),
	email: text(),
	phone: text(),
	address: text(),
	emergencyName: text("emergency_name"),
	emergencyRelationship: text("emergency_relationship"),
	emergencyPhone: text("emergency_phone"),
	primaryDiagnosis: text("primary_diagnosis"),
	referringProvider: text("referring_provider"),
	currentMedications: text("current_medications"),
	allergies: text(),
	medicalHistory: text("medical_history"),
	contraindications: jsonb().default({}),
	status: text().default('active'),
	isArchived: boolean("is_archived").default(false),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	pgPolicy("within_patients_authorized", { as: "permissive", for: "all", to: ["authenticated"], using: sql`is_within_authorized()`, withCheck: sql`is_within_authorized()`  }),
]);

export const withinSessions = pgTable("within_sessions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	patientId: uuid("patient_id"),
	sessionDate: date("session_date"),
	sessionNumber: integer("session_number"),
	provider: text(),
	route: text(),
	drug: text().default('ketamine'),
	weightKg: numeric("weight_kg"),
	doseMg: numeric("dose_mg"),
	doseMgKg: numeric("dose_mg_kg"),
	durationMin: integer("duration_min"),
	lotNumber: text("lot_number"),
	lotExpiration: date("lot_expiration"),
	preVitals: jsonb("pre_vitals").default({}),
	postVitals: jsonb("post_vitals").default({}),
	intraVitals: jsonb("intra_vitals").default([]),
	lastMealTime: time("last_meal_time"),
	medsToday: text("meds_today"),
	preScreeningNotes: text("pre_screening_notes"),
	goDecision: boolean("go_decision").default(false),
	sideEffects: jsonb("side_effects").default({}),
	adjunctMeds: text("adjunct_meds"),
	sessionNotes: text("session_notes"),
	dischargeCriteria: jsonb("discharge_criteria").default({}),
	dischargeTime: time("discharge_time"),
	dischargeNotes: text("discharge_notes"),
	status: text().default('completed'),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	foreignKey({
			columns: [table.patientId],
			foreignColumns: [withinPatients.id],
			name: "within_sessions_patient_id_fkey"
		}),
	pgPolicy("within_sessions_authorized", { as: "permissive", for: "all", to: ["authenticated"], using: sql`is_within_authorized()`, withCheck: sql`is_within_authorized()`  }),
]);

export const withinAssessments = pgTable("within_assessments", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	patientId: uuid("patient_id"),
	assessmentDate: date("assessment_date"),
	measure: text().notNull(),
	score: integer(),
	itemScores: jsonb("item_scores"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	foreignKey({
			columns: [table.patientId],
			foreignColumns: [withinPatients.id],
			name: "within_assessments_patient_id_fkey"
		}),
	pgPolicy("within_assessments_authorized", { as: "permissive", for: "all", to: ["authenticated"], using: sql`is_within_authorized()`, withCheck: sql`is_within_authorized()`  }),
]);

export const withinAppointments = pgTable("within_appointments", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	patientId: uuid("patient_id"),
	apptDate: date("appt_date"),
	apptTime: time("appt_time"),
	apptType: text("appt_type"),
	provider: text(),
	room: text(),
	notes: text(),
	status: text().default('scheduled'),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	foreignKey({
			columns: [table.patientId],
			foreignColumns: [withinPatients.id],
			name: "within_appointments_patient_id_fkey"
		}),
	pgPolicy("within_appointments_authorized", { as: "permissive", for: "all", to: ["authenticated"], using: sql`is_within_authorized()`, withCheck: sql`is_within_authorized()`  }),
]);

export const withinConsents = pgTable("within_consents", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	patientId: uuid("patient_id"),
	documentType: text("document_type"),
	sentDate: date("sent_date"),
	signedDate: date("signed_date"),
	status: text().default('draft'),
	documentUrl: text("document_url"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	foreignKey({
			columns: [table.patientId],
			foreignColumns: [withinPatients.id],
			name: "within_consents_patient_id_fkey"
		}),
	pgPolicy("within_consents_authorized", { as: "permissive", for: "all", to: ["authenticated"], using: sql`is_within_authorized()`, withCheck: sql`is_within_authorized()`  }),
]);

export const withinInventory = pgTable("within_inventory", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	entryDate: date("entry_date"),
	type: text().notNull(),
	lotNumber: text("lot_number"),
	quantity: numeric(),
	witness: text(),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	pgPolicy("within_inventory_authorized", { as: "permissive", for: "all", to: ["authenticated"], using: sql`is_within_authorized()`, withCheck: sql`is_within_authorized()`  }),
]);

export const withinInvoices = pgTable("within_invoices", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	patientId: uuid("patient_id"),
	invoiceNumber: text("invoice_number"),
	invoiceDate: date("invoice_date"),
	amount: numeric().default('0'),
	status: text().default('pending'),
	lineItems: jsonb("line_items").default([]),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	foreignKey({
			columns: [table.patientId],
			foreignColumns: [withinPatients.id],
			name: "within_invoices_patient_id_fkey"
		}),
	pgPolicy("within_invoices_authorized", { as: "permissive", for: "all", to: ["authenticated"], using: sql`is_within_authorized()`, withCheck: sql`is_within_authorized()`  }),
]);

export const stripePayments = pgTable("stripe_payments", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	stripePaymentIntentId: text("stripe_payment_intent_id"),
	paymentType: text("payment_type").default('one_time').notNull(),
	referenceType: text("reference_type").default('crm_invoice').notNull(),
	referenceId: text("reference_id").notNull(),
	amount: numeric().notNull(),
	originalAmount: numeric("original_amount"),
	feeAmount: numeric("fee_amount").default('0'),
	status: text().default('pending'),
	personId: text("person_id"),
	personName: text("person_name"),
	buyerEmail: text("buyer_email"),
	ledgerId: uuid("ledger_id"),
	errorMessage: text("error_message"),
	isTest: boolean("is_test").default(false),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	pgPolicy("Authenticated insert stripe_payments", { as: "permissive", for: "insert", to: ["authenticated"], withCheck: sql`true`  }),
	pgPolicy("Authenticated read stripe_payments", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Service role full access stripe_payments", { as: "permissive", for: "all", to: ["service_role"] }),
]);

export const crmInvoices = pgTable("crm_invoices", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	businessLine: text("business_line").notNull(),
	leadId: uuid("lead_id"),
	invoiceNumber: text("invoice_number").notNull(),
	invoiceDate: date("invoice_date").default(sql`CURRENT_DATE`),
	dueDate: date("due_date"),
	subtotal: numeric().default('0').notNull(),
	discountAmount: numeric("discount_amount").default('0'),
	discountLabel: text("discount_label"),
	taxAmount: numeric("tax_amount").default('0'),
	total: numeric().default('0').notNull(),
	status: text().default('draft'),
	stripePaymentLinkId: text("stripe_payment_link_id"),
	stripePaymentLinkUrl: text("stripe_payment_link_url"),
	stripePaymentIntentId: text("stripe_payment_intent_id"),
	paidAt: timestamp("paid_at", { withTimezone: true, mode: 'string' }),
	paidAmount: numeric("paid_amount"),
	clientName: text("client_name"),
	clientEmail: text("client_email"),
	clientPhone: text("client_phone"),
	notes: text(),
	createdBy: uuid("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_crm_invoices_business_line").using("btree", table.businessLine.asc().nullsLast().op("text_ops")),
	index("idx_crm_invoices_lead_id").using("btree", table.leadId.asc().nullsLast().op("uuid_ops")),
	index("idx_crm_invoices_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.leadId],
			foreignColumns: [crmLeads.id],
			name: "crm_invoices_lead_id_fkey"
		}),
	pgPolicy("Authenticated users can delete invoices", { as: "permissive", for: "delete", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Authenticated users can insert invoices", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("Authenticated users can read invoices", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Authenticated users can update invoices", { as: "permissive", for: "update", to: ["authenticated"] }),
	pgPolicy("Service role full access invoices", { as: "permissive", for: "all", to: ["service_role"] }),
	check("crm_invoices_status_check", sql`status = ANY (ARRAY['draft'::text, 'sent'::text, 'viewed'::text, 'paid'::text, 'void'::text])`),
]);

export const crmInvoiceLineItems = pgTable("crm_invoice_line_items", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	invoiceId: uuid("invoice_id").notNull(),
	servicePackageId: uuid("service_package_id"),
	description: text().notNull(),
	quantity: integer().default(1),
	unitPrice: numeric("unit_price").notNull(),
	total: numeric().notNull(),
	sortOrder: integer("sort_order").default(0),
}, (table) => [
	index("idx_crm_invoice_items_invoice").using("btree", table.invoiceId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.invoiceId],
			foreignColumns: [crmInvoices.id],
			name: "crm_invoice_line_items_invoice_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.servicePackageId],
			foreignColumns: [crmServicePackages.id],
			name: "crm_invoice_line_items_service_package_id_fkey"
		}),
	pgPolicy("Authenticated users can delete invoice items", { as: "permissive", for: "delete", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Authenticated users can insert invoice items", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("Authenticated users can read invoice items", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Authenticated users can update invoice items", { as: "permissive", for: "update", to: ["authenticated"] }),
	pgPolicy("Service role full access invoice_items", { as: "permissive", for: "all", to: ["service_role"] }),
]);

export const crmActivities = pgTable("crm_activities", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	leadId: uuid("lead_id").notNull(),
	activityType: text("activity_type").notNull(),
	description: text(),
	oldStageId: uuid("old_stage_id"),
	newStageId: uuid("new_stage_id"),
	createdBy: uuid("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	metadata: jsonb().default({}),
}, (table) => [
	index("idx_crm_activities_lead_id").using("btree", table.leadId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.leadId],
			foreignColumns: [crmLeads.id],
			name: "crm_activities_lead_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.newStageId],
			foreignColumns: [crmPipelineStages.id],
			name: "crm_activities_new_stage_id_fkey"
		}),
	foreignKey({
			columns: [table.oldStageId],
			foreignColumns: [crmPipelineStages.id],
			name: "crm_activities_old_stage_id_fkey"
		}),
	pgPolicy("Authenticated users can insert activities", { as: "permissive", for: "insert", to: ["authenticated"], withCheck: sql`true`  }),
	pgPolicy("Authenticated users can read activities", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Service role full access activities", { as: "permissive", for: "all", to: ["service_role"] }),
	check("crm_activities_activity_type_check", sql`activity_type = ANY (ARRAY['note'::text, 'call'::text, 'email'::text, 'stage_change'::text, 'sms'::text, 'meeting'::text, 'system'::text, 'payment'::text])`),
]);

export const crmServicePackages = pgTable("crm_service_packages", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	businessLine: text("business_line").default('within').notNull(),
	name: text().notNull(),
	slug: text().notNull(),
	priceRegular: numeric("price_regular").notNull(),
	pricePromo: numeric("price_promo"),
	description: text(),
	includes: jsonb(),
	isActive: boolean("is_active").default(true),
	sortOrder: integer("sort_order").default(0),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	category: text(),
}, (table) => [
	index("crm_service_packages_category_idx").using("btree", table.category.asc().nullsLast().op("text_ops")),
	unique("crm_service_packages_slug_key").on(table.slug),
	pgPolicy("Authenticated users can read CRM packages", { as: "permissive", for: "select", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Service role full access packages", { as: "permissive", for: "all", to: ["service_role"] }),
]);

export const crmProposalItems = pgTable("crm_proposal_items", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	proposalId: uuid("proposal_id").notNull(),
	category: text().notNull(),
	description: text().notNull(),
	quantity: integer().default(1),
	unitPrice: numeric("unit_price").notNull(),
	total: numeric().notNull(),
	sortOrder: integer("sort_order").default(0),
}, (table) => [
	index("idx_crm_proposal_items_proposal").using("btree", table.proposalId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.proposalId],
			foreignColumns: [crmProposals.id],
			name: "crm_proposal_items_proposal_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("Anon read sent proposal items", { as: "permissive", for: "select", to: ["anon"], using: sql`(EXISTS ( SELECT 1
   FROM crm_proposals
  WHERE ((crm_proposals.id = crm_proposal_items.proposal_id) AND (crm_proposals.status = 'sent'::text))))` }),
	pgPolicy("Auth delete proposal items", { as: "permissive", for: "delete", to: ["authenticated"] }),
	pgPolicy("Auth insert proposal items", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("Auth read proposal items", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Auth update proposal items", { as: "permissive", for: "update", to: ["authenticated"] }),
	pgPolicy("Service role proposal items", { as: "permissive", for: "all", to: ["service_role"] }),
]);

export const crmVenueCatalog = pgTable("crm_venue_catalog", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	category: text().notNull(),
	name: text().notNull(),
	description: text(),
	unitPrice: numeric("unit_price").notNull(),
	unit: text().default('flat').notNull(),
	minimumQty: integer("minimum_qty").default(1),
	capacity: text(),
	isActive: boolean("is_active").default(true),
	sortOrder: integer("sort_order").default(0),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	pgPolicy("Anon read venue catalog", { as: "permissive", for: "select", to: ["anon"], using: sql`true` }),
	pgPolicy("Auth manage venue catalog", { as: "permissive", for: "all", to: ["authenticated"] }),
	pgPolicy("Auth read venue catalog", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Service role venue catalog", { as: "permissive", for: "all", to: ["service_role"] }),
]);

export const crmAdSpend = pgTable("crm_ad_spend", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	platform: text().notNull(),
	campaignId: text("campaign_id"),
	campaignName: text("campaign_name"),
	date: date().notNull(),
	impressions: integer().default(0),
	clicks: integer().default(0),
	spend: numeric().default('0').notNull(),
	conversions: integer().default(0),
	costPerClick: numeric("cost_per_click"),
	businessLine: text("business_line"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	unique("crm_ad_spend_platform_campaign_id_date_key").on(table.platform, table.campaignId, table.date),
	pgPolicy("Auth insert ad spend", { as: "permissive", for: "insert", to: ["authenticated"], withCheck: sql`true`  }),
	pgPolicy("Auth read ad spend", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Service role ad spend", { as: "permissive", for: "all", to: ["service_role"] }),
]);

export const crmProposals = pgTable("crm_proposals", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	leadId: uuid("lead_id").notNull(),
	proposalNumber: text("proposal_number").notNull(),
	title: text().notNull(),
	eventDate: date("event_date"),
	eventType: text("event_type"),
	guestCount: integer("guest_count"),
	setupTime: text("setup_time"),
	eventStart: text("event_start"),
	eventEnd: text("event_end"),
	teardownTime: text("teardown_time"),
	subtotal: numeric().default('0'),
	discountAmount: numeric("discount_amount").default('0'),
	taxAmount: numeric("tax_amount").default('0'),
	total: numeric().default('0'),
	status: text().default('draft'),
	validUntil: date("valid_until"),
	notes: text(),
	terms: text(),
	invoiceId: uuid("invoice_id"),
	createdBy: uuid("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	paymentLinkId: text("payment_link_id"),
	paymentLinkUrl: text("payment_link_url"),
	stripeCheckoutSessionId: text("stripe_checkout_session_id"),
	stripePaymentIntentId: text("stripe_payment_intent_id"),
	paidAt: timestamp("paid_at", { withTimezone: true, mode: 'string' }),
	paidAmountCents: integer("paid_amount_cents"),
	sentAt: timestamp("sent_at", { withTimezone: true, mode: 'string' }),
	sentToEmail: text("sent_to_email"),
	paymentLinkCardId: text("payment_link_card_id"),
	paymentLinkCardUrl: text("payment_link_card_url"),
	signwellDocumentId: text("signwell_document_id"),
	contractSignedAt: timestamp("contract_signed_at", { withTimezone: true, mode: 'string' }),
	contractSignedByName: text("contract_signed_by_name"),
	contractSignedByEmail: text("contract_signed_by_email"),
	depositPercent: integer("deposit_percent").default(50),
	balanceReminderSentAt: timestamp("balance_reminder_sent_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("crm_proposals_checkout_session_idx").using("btree", table.stripeCheckoutSessionId.asc().nullsLast().op("text_ops")),
	index("crm_proposals_payment_link_idx").using("btree", table.paymentLinkId.asc().nullsLast().op("text_ops")),
	index("idx_crm_proposals_lead_id").using("btree", table.leadId.asc().nullsLast().op("uuid_ops")),
	index("idx_crm_proposals_signwell_document_id").using("btree", table.signwellDocumentId.asc().nullsLast().op("text_ops")).where(sql`(signwell_document_id IS NOT NULL)`),
	index("idx_crm_proposals_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.leadId],
			foreignColumns: [crmLeads.id],
			name: "crm_proposals_lead_id_fkey"
		}),
	pgPolicy("Anon read sent proposals", { as: "permissive", for: "select", to: ["anon"], using: sql`(status = 'sent'::text)` }),
	pgPolicy("Auth delete proposals", { as: "permissive", for: "delete", to: ["authenticated"] }),
	pgPolicy("Auth insert proposals", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("Auth read proposals", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Auth update proposals", { as: "permissive", for: "update", to: ["authenticated"] }),
	pgPolicy("Service role proposals", { as: "permissive", for: "all", to: ["service_role"] }),
	check("crm_proposals_status_check", sql`status = ANY (ARRAY['draft'::text, 'sent'::text, 'accepted'::text, 'declined'::text, 'expired'::text, 'paid'::text])`),
]);

export const crmNumberSequences = pgTable("crm_number_sequences", {
	prefix: text().primaryKey().notNull(),
	lastNumber: integer("last_number").default(0).notNull(),
}, (table) => [
	pgPolicy("Auth read sequences", { as: "permissive", for: "select", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Service role full sequences", { as: "permissive", for: "all", to: ["service_role"] }),
]);

export const schedulingBookings = pgTable("scheduling_bookings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	profileId: uuid("profile_id"),
	leadId: uuid("lead_id"),
	bookerName: text("booker_name").notNull(),
	bookerEmail: text("booker_email").notNull(),
	bookerPhone: text("booker_phone"),
	startDatetime: timestamp("start_datetime", { withTimezone: true, mode: 'string' }).notNull(),
	endDatetime: timestamp("end_datetime", { withTimezone: true, mode: 'string' }).notNull(),
	googleEventId: text("google_event_id"),
	status: text().default('confirmed'),
	cancelReason: text("cancel_reason"),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	eventTypeId: uuid("event_type_id"),
	bookingToken: uuid("booking_token").defaultRandom().notNull(),
	rescheduledFrom: uuid("rescheduled_from"),
	cancelledAt: timestamp("cancelled_at", { withTimezone: true, mode: 'string' }),
	bookerTimezone: text("booker_timezone"),
	reminder24HSentAt: timestamp("reminder_24h_sent_at", { withTimezone: true, mode: 'string' }),
	reminder1HSentAt: timestamp("reminder_1h_sent_at", { withTimezone: true, mode: 'string' }),
	serviceId: uuid("service_id"),
	spaceId: uuid("space_id"),
	packageSessionId: uuid("package_session_id"),
	staffUserId: uuid("staff_user_id"),
	createdByAdminId: uuid("created_by_admin_id"),
	facilitatorId: uuid("facilitator_id"),
}, (table) => [
	index("idx_sched_bookings_service").using("btree", table.serviceId.asc().nullsLast().op("uuid_ops")),
	index("idx_sched_bookings_space").using("btree", table.spaceId.asc().nullsLast().op("uuid_ops")),
	index("idx_sched_bookings_staff").using("btree", table.staffUserId.asc().nullsLast().op("uuid_ops")),
	index("idx_scheduling_bookings_profile").using("btree", table.profileId.asc().nullsLast().op("uuid_ops")),
	index("idx_scheduling_bookings_start").using("btree", table.startDatetime.asc().nullsLast().op("timestamptz_ops")),
	index("scheduling_bookings_facilitator_idx").using("btree", table.facilitatorId.asc().nullsLast().op("uuid_ops")).where(sql`(facilitator_id IS NOT NULL)`),
	uniqueIndex("scheduling_bookings_facilitator_slot_unique").using("btree", table.facilitatorId.asc().nullsLast().op("timestamptz_ops"), table.startDatetime.asc().nullsLast().op("uuid_ops")).where(sql`((cancelled_at IS NULL) AND (facilitator_id IS NOT NULL))`),
	index("scheduling_bookings_lead_idx").using("btree", table.leadId.asc().nullsLast().op("uuid_ops")),
	uniqueIndex("scheduling_bookings_slot_unique").using("btree", table.profileId.asc().nullsLast().op("uuid_ops"), table.eventTypeId.asc().nullsLast().op("timestamptz_ops"), table.startDatetime.asc().nullsLast().op("timestamptz_ops")).where(sql`(cancelled_at IS NULL)`),
	uniqueIndex("scheduling_bookings_staff_slot_unique").using("btree", table.staffUserId.asc().nullsLast().op("timestamptz_ops"), table.startDatetime.asc().nullsLast().op("uuid_ops")).where(sql`((cancelled_at IS NULL) AND (staff_user_id IS NOT NULL))`),
	index("scheduling_bookings_token_idx").using("btree", table.bookingToken.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.createdByAdminId],
			foreignColumns: [appUsers.id],
			name: "scheduling_bookings_created_by_admin_id_fkey"
		}),
	foreignKey({
			columns: [table.eventTypeId],
			foreignColumns: [schedulingEventTypes.id],
			name: "scheduling_bookings_event_type_id_fkey"
		}).onDelete("restrict"),
	foreignKey({
			columns: [table.facilitatorId],
			foreignColumns: [facilitators.id],
			name: "scheduling_bookings_facilitator_id_fkey"
		}),
	foreignKey({
			columns: [table.leadId],
			foreignColumns: [crmLeads.id],
			name: "scheduling_bookings_lead_id_fkey"
		}),
	foreignKey({
			columns: [table.packageSessionId],
			foreignColumns: [clientPackageSessions.id],
			name: "scheduling_bookings_package_session_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.profileId],
			foreignColumns: [schedulingProfiles.id],
			name: "scheduling_bookings_profile_id_fkey"
		}),
	foreignKey({
			columns: [table.rescheduledFrom],
			foreignColumns: [table.id],
			name: "scheduling_bookings_rescheduled_from_fkey"
		}),
	foreignKey({
			columns: [table.serviceId],
			foreignColumns: [services.id],
			name: "scheduling_bookings_service_id_fkey"
		}),
	foreignKey({
			columns: [table.spaceId],
			foreignColumns: [spaces.id],
			name: "scheduling_bookings_space_id_fkey"
		}),
	foreignKey({
			columns: [table.staffUserId],
			foreignColumns: [appUsers.id],
			name: "scheduling_bookings_staff_user_id_fkey"
		}),
	pgPolicy("Anon read own bookings", { as: "permissive", for: "select", to: ["anon"], using: sql`true` }),
	pgPolicy("Auth read bookings", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Auth update bookings", { as: "permissive", for: "update", to: ["authenticated"] }),
	pgPolicy("Service role bookings", { as: "permissive", for: "all", to: ["service_role"] }),
	check("scheduling_bookings_assignee_chk", sql`(cancelled_at IS NOT NULL) OR (profile_id IS NOT NULL) OR (staff_user_id IS NOT NULL) OR (facilitator_id IS NOT NULL)`),
	check("scheduling_bookings_status_check", sql`status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text, 'completed'::text, 'no_show'::text])`),
]);

export const schedulingProfiles = pgTable("scheduling_profiles", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	appUserId: uuid("app_user_id").notNull(),
	bookingSlug: text("booking_slug").notNull(),
	googleCalendarId: text("google_calendar_id").default('primary'),
	googleRefreshToken: text("google_refresh_token"),
	googleAccessToken: text("google_access_token"),
	tokenExpiresAt: timestamp("token_expires_at", { withTimezone: true, mode: 'string' }),
	isBookable: boolean("is_bookable").default(false),
	meetingDuration: integer("meeting_duration").default(30),
	bufferMinutes: integer("buffer_minutes").default(15),
	availableHours: jsonb("available_hours").default({"fri":{"end":"17:00","start":"09:00"},"mon":{"end":"17:00","start":"09:00"},"thu":{"end":"17:00","start":"09:00"},"tue":{"end":"17:00","start":"09:00"},"wed":{"end":"17:00","start":"09:00"}}),
	advanceDays: integer("advance_days").default(30),
	meetingTitle: text("meeting_title").default('Free Consultation — Within Center'),
	meetingDescription: text("meeting_description").default('Free phone consultation to discuss your goals and treatment options.'),
	timezone: text().default('America/Chicago'),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	foreignKey({
			columns: [table.appUserId],
			foreignColumns: [appUsers.id],
			name: "scheduling_profiles_app_user_id_fkey"
		}),
	unique("scheduling_profiles_booking_slug_key").on(table.bookingSlug),
	pgPolicy("Anon read bookable profiles", { as: "permissive", for: "select", to: ["anon"], using: sql`(is_bookable = true)` }),
	pgPolicy("Auth insert profiles", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("Auth read profiles", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Auth update profiles", { as: "permissive", for: "update", to: ["authenticated"] }),
	pgPolicy("Service role profiles", { as: "permissive", for: "all", to: ["service_role"] }),
]);

export const permissions = pgTable("permissions", {
	key: text().primaryKey().notNull(),
	label: text().notNull(),
	category: text(),
	description: text(),
	sortOrder: integer("sort_order").default(100),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	pgPolicy("permissions_read", { as: "permissive", for: "select", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("permissions_write", { as: "permissive", for: "all", to: ["public"] }),
]);

export const jobTitles = pgTable("job_titles", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	description: text(),
	color: text(),
	isArchived: boolean("is_archived").default(false).notNull(),
	createdBy: uuid("created_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [appUsers.id],
			name: "job_titles_created_by_fkey"
		}),
	unique("job_titles_name_key").on(table.name),
	pgPolicy("job_titles_read", { as: "permissive", for: "select", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("job_titles_write", { as: "permissive", for: "all", to: ["public"] }),
]);

export const schedulingEventTypes = pgTable("scheduling_event_types", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	profileId: uuid("profile_id").notNull(),
	slug: text().notNull(),
	name: text().notNull(),
	description: text(),
	durationMinutes: integer("duration_minutes").default(30).notNull(),
	bufferMinutes: integer("buffer_minutes").default(0).notNull(),
	advanceDays: integer("advance_days").default(30).notNull(),
	minNoticeMinutes: integer("min_notice_minutes").default(60).notNull(),
	locationType: text("location_type").default('video').notNull(),
	locationDetail: text("location_detail"),
	availableHours: jsonb("available_hours"),
	color: text(),
	notifySmsOnBooking: boolean("notify_sms_on_booking").default(false).notNull(),
	isActive: boolean("is_active").default(true).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("scheduling_event_types_profile_idx").using("btree", table.profileId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.profileId],
			foreignColumns: [schedulingProfiles.id],
			name: "scheduling_event_types_profile_id_fkey"
		}).onDelete("cascade"),
	unique("scheduling_event_types_profile_id_slug_key").on(table.profileId, table.slug),
	pgPolicy("event_types_admin_all", { as: "permissive", for: "all", to: ["public"], using: sql`((EXISTS ( SELECT 1
   FROM (app_users u
     JOIN user_permissions up ON ((up.app_user_id = u.id)))
  WHERE ((u.auth_user_id = auth.uid()) AND (up.permission_key = 'manage_scheduling'::text) AND (up.granted = true)))) OR (EXISTS ( SELECT 1
   FROM app_users u
  WHERE ((u.auth_user_id = auth.uid()) AND (u.role = ANY (ARRAY['admin'::text, 'oracle'::text]))))))` }),
	pgPolicy("event_types_owner_all", { as: "permissive", for: "all", to: ["public"] }),
	pgPolicy("event_types_public_read", { as: "permissive", for: "select", to: ["public"] }),
	pgPolicy("event_types_service_role", { as: "permissive", for: "all", to: ["public"] }),
]);

export const beds = pgTable("beds", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	spaceId: uuid("space_id").notNull(),
	label: text().notNull(),
	bedType: text("bed_type").notNull(),
	maxGuests: integer("max_guests").default(1).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	isArchived: boolean("is_archived").default(false).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	nightlyRateCents: integer("nightly_rate_cents").default(0).notNull(),
}, (table) => [
	index("idx_beds_space").using("btree", table.spaceId.asc().nullsLast().op("uuid_ops")).where(sql`(is_archived = false)`),
	foreignKey({
			columns: [table.spaceId],
			foreignColumns: [spaces.id],
			name: "beds_space_id_fkey"
		}).onDelete("cascade"),
	unique("beds_space_id_label_key").on(table.spaceId, table.label),
	check("beds_bed_type_check", sql`bed_type = ANY (ARRAY['king'::text, 'queen'::text, 'double'::text, 'twin'::text, 'bunk_top'::text, 'bunk_bottom'::text])`),
	check("beds_max_guests_check", sql`max_guests >= 1`),
	check("beds_nightly_rate_cents_check", sql`nightly_rate_cents >= 0`),
]);

export const clientPackages = pgTable("client_packages", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	leadId: uuid("lead_id").notNull(),
	name: text().notNull(),
	occupancyRate: text("occupancy_rate").default('private').notNull(),
	status: text().default('active').notNull(),
	priceCents: integer("price_cents").default(0).notNull(),
	purchasedAt: timestamp("purchased_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	paidAt: timestamp("paid_at", { withTimezone: true, mode: 'string' }),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_client_packages_lead").using("btree", table.leadId.asc().nullsLast().op("uuid_ops")),
	index("idx_client_packages_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.leadId],
			foreignColumns: [crmLeads.id],
			name: "client_packages_lead_id_fkey"
		}).onDelete("cascade"),
	check("client_packages_occupancy_rate_check", sql`occupancy_rate = ANY (ARRAY['private'::text, 'shared'::text])`),
	check("client_packages_price_cents_check", sql`price_cents >= 0`),
	check("client_packages_status_check", sql`status = ANY (ARRAY['active'::text, 'completed'::text, 'cancelled'::text])`),
]);

export const admissionsAnalyses = pgTable("admissions_analyses", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	status: text().default('processing').notNull(),
	model: text(),
	fileName: text("file_name"),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	fileSizeBytes: bigint("file_size_bytes", { mode: "number" }),
	result: jsonb(),
	error: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	completedAt: timestamp("completed_at", { withTimezone: true, mode: 'string' }),
}, (table) => [
	index("idx_admissions_analyses_created_at").using("btree", table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	check("admissions_analyses_status_check", sql`status = ANY (ARRAY['processing'::text, 'done'::text, 'error'::text])`),
]);

export const emailTypeApprovalConfig = pgTable("email_type_approval_config", {
	emailType: text("email_type").primaryKey().notNull(),
	requiresApproval: boolean("requires_approval").default(true).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	pgPolicy("service role only", { as: "permissive", for: "all", to: ["service_role"], using: sql`true`, withCheck: sql`true`  }),
]);

export const clientPackageSessions = pgTable("client_package_sessions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	packageId: uuid("package_id").notNull(),
	serviceId: uuid("service_id").notNull(),
	status: text().default('unscheduled').notNull(),
	bookingId: uuid("booking_id"),
	scheduledAt: timestamp("scheduled_at", { withTimezone: true, mode: 'string' }),
	completedAt: timestamp("completed_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_pkg_sessions_booking").using("btree", table.bookingId.asc().nullsLast().op("uuid_ops")),
	index("idx_pkg_sessions_package").using("btree", table.packageId.asc().nullsLast().op("uuid_ops")),
	index("idx_pkg_sessions_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.bookingId],
			foreignColumns: [schedulingBookings.id],
			name: "client_package_sessions_booking_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.packageId],
			foreignColumns: [clientPackages.id],
			name: "client_package_sessions_package_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.serviceId],
			foreignColumns: [services.id],
			name: "client_package_sessions_service_id_fkey"
		}),
	check("client_package_sessions_status_check", sql`status = ANY (ARRAY['unscheduled'::text, 'scheduled'::text, 'completed'::text, 'cancelled'::text])`),
]);

export const clientStays = pgTable("client_stays", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	leadId: uuid("lead_id").notNull(),
	bedId: uuid("bed_id"),
	packageId: uuid("package_id"),
	checkInAt: timestamp("check_in_at", { withTimezone: true, mode: 'string' }).notNull(),
	checkOutAt: timestamp("check_out_at", { withTimezone: true, mode: 'string' }).notNull(),
	status: text().default('upcoming').notNull(),
	googleEventId: text("google_event_id"),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_client_stays_bed").using("btree", table.bedId.asc().nullsLast().op("timestamptz_ops"), table.checkInAt.asc().nullsLast().op("timestamptz_ops")),
	index("idx_client_stays_lead").using("btree", table.leadId.asc().nullsLast().op("uuid_ops")),
	index("idx_client_stays_window").using("btree", table.status.asc().nullsLast().op("text_ops"), table.checkInAt.asc().nullsLast().op("text_ops"), table.checkOutAt.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.bedId],
			foreignColumns: [beds.id],
			name: "client_stays_bed_id_fkey"
		}),
	foreignKey({
			columns: [table.leadId],
			foreignColumns: [crmLeads.id],
			name: "client_stays_lead_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.packageId],
			foreignColumns: [clientPackages.id],
			name: "client_stays_package_id_fkey"
		}).onDelete("set null"),
	check("client_stays_check", sql`check_out_at > check_in_at`),
	check("client_stays_status_check", sql`status = ANY (ARRAY['upcoming'::text, 'active'::text, 'completed'::text, 'cancelled'::text])`),
]);

export const facilitators = pgTable("facilitators", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	firstName: text("first_name").notNull(),
	lastName: text("last_name"),
	email: text(),
	phone: text(),
	notes: text(),
	isActive: boolean("is_active").default(true).notNull(),
	sortOrder: integer("sort_order").default(100).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	pgPolicy("Authenticated users can read facilitators", { as: "permissive", for: "select", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Authenticated users can write facilitators", { as: "permissive", for: "all", to: ["authenticated"] }),
]);

export const services = pgTable("services", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	name: text().notNull(),
	slug: text().notNull(),
	description: text(),
	durationMinutes: integer("duration_minutes").notNull(),
	defaultPriceCents: integer("default_price_cents").default(0).notNull(),
	requiresUpfrontPayment: boolean("requires_upfront_payment").default(false).notNull(),
	isActive: boolean("is_active").default(true).notNull(),
	sortOrder: integer("sort_order").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	isGroupClass: boolean("is_group_class").default(false).notNull(),
	maxCapacity: integer("max_capacity"),
}, (table) => [
	index("idx_services_active_sort").using("btree", table.isActive.asc().nullsLast().op("int4_ops"), table.sortOrder.asc().nullsLast().op("int4_ops")),
	unique("services_slug_key").on(table.slug),
	check("services_default_price_cents_check", sql`default_price_cents >= 0`),
	check("services_duration_minutes_check", sql`duration_minutes > 0`),
	check("services_max_capacity_check", sql`(max_capacity IS NULL) OR (max_capacity > 0)`),
]);

export const schedulingBookingAttendees = pgTable("scheduling_booking_attendees", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	bookingId: uuid("booking_id").notNull(),
	leadId: uuid("lead_id").notNull(),
	packageSessionId: uuid("package_session_id"),
	status: text().default('confirmed').notNull(),
	attendedAt: timestamp("attended_at", { withTimezone: true, mode: 'string' }),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_attendees_booking").using("btree", table.bookingId.asc().nullsLast().op("uuid_ops")),
	index("idx_attendees_lead").using("btree", table.leadId.asc().nullsLast().op("uuid_ops")),
	index("idx_attendees_session").using("btree", table.packageSessionId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.bookingId],
			foreignColumns: [schedulingBookings.id],
			name: "scheduling_booking_attendees_booking_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.leadId],
			foreignColumns: [crmLeads.id],
			name: "scheduling_booking_attendees_lead_id_fkey"
		}),
	foreignKey({
			columns: [table.packageSessionId],
			foreignColumns: [clientPackageSessions.id],
			name: "scheduling_booking_attendees_package_session_id_fkey"
		}).onDelete("set null"),
	unique("scheduling_booking_attendees_booking_id_lead_id_key").on(table.bookingId, table.leadId),
	pgPolicy("Auth read attendees", { as: "permissive", for: "select", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Auth update attendees", { as: "permissive", for: "update", to: ["authenticated"] }),
	pgPolicy("Service role attendees", { as: "permissive", for: "all", to: ["service_role"] }),
	check("scheduling_booking_attendees_status_check", sql`status = ANY (ARRAY['confirmed'::text, 'cancelled'::text, 'attended'::text, 'no_show'::text])`),
]);

export const clientIntegrationNotes = pgTable("client_integration_notes", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	leadId: uuid("lead_id").notNull(),
	authorAppUserId: uuid("author_app_user_id"),
	content: text().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("client_integration_notes_lead_idx").using("btree", table.leadId.asc().nullsLast().op("timestamptz_ops"), table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	foreignKey({
			columns: [table.authorAppUserId],
			foreignColumns: [appUsers.id],
			name: "client_integration_notes_author_app_user_id_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.leadId],
			foreignColumns: [crmLeads.id],
			name: "client_integration_notes_lead_id_fkey"
		}).onDelete("cascade"),
	pgPolicy("staff insert integration notes", { as: "permissive", for: "insert", to: ["authenticated"], withCheck: sql`(EXISTS ( SELECT 1
   FROM app_users
  WHERE ((app_users.auth_user_id = auth.uid()) AND (app_users.role = ANY (ARRAY['admin'::text, 'staff'::text, 'oracle'::text])))))`  }),
	pgPolicy("staff read integration notes", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("staff update integration notes", { as: "permissive", for: "update", to: ["authenticated"] }),
]);

export const orgChartState = pgTable("org_chart_state", {
	id: text().default('main').primaryKey().notNull(),
	chartData: jsonb("chart_data").default({}).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedByEmail: text("updated_by_email"),
}, (table) => [
	pgPolicy("org_chart auth write", { as: "permissive", for: "all", to: ["authenticated"], using: sql`true`, withCheck: sql`true`  }),
	pgPolicy("org_chart public read", { as: "permissive", for: "select", to: ["anon", "authenticated"] }),
	check("org_chart_state_id_check", sql`id = 'main'::text`),
]);

export const eventSpaceReservations = pgTable("event_space_reservations", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	leadId: uuid("lead_id").notNull(),
	spaceId: uuid("space_id").notNull(),
	startAt: timestamp("start_at", { withTimezone: true, mode: 'string' }).notNull(),
	endAt: timestamp("end_at", { withTimezone: true, mode: 'string' }).notNull(),
	setupMinutes: integer("setup_minutes").default(0).notNull(),
	breakdownMinutes: integer("breakdown_minutes").default(0).notNull(),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_esr_lead").using("btree", table.leadId.asc().nullsLast().op("uuid_ops")),
	index("idx_esr_space").using("btree", table.spaceId.asc().nullsLast().op("timestamptz_ops"), table.startAt.asc().nullsLast().op("timestamptz_ops")),
	index("idx_esr_window").using("btree", table.startAt.asc().nullsLast().op("timestamptz_ops"), table.endAt.asc().nullsLast().op("timestamptz_ops")),
	foreignKey({
			columns: [table.leadId],
			foreignColumns: [crmLeads.id],
			name: "event_space_reservations_lead_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.spaceId],
			foreignColumns: [spaces.id],
			name: "event_space_reservations_space_id_fkey"
		}),
	pgPolicy("esr authenticated read", { as: "permissive", for: "select", to: ["authenticated"], using: sql`true` }),
	pgPolicy("esr authenticated write", { as: "permissive", for: "all", to: ["authenticated"] }),
	check("event_space_reservations_breakdown_minutes_check", sql`breakdown_minutes >= 0`),
	check("event_space_reservations_check", sql`end_at > start_at`),
	check("event_space_reservations_setup_minutes_check", sql`setup_minutes >= 0`),
]);

export const withinRetreatAgreements = pgTable("within_retreat_agreements", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	leadId: uuid("lead_id").notNull(),
	packageId: uuid("package_id"),
	signwellDocumentId: text("signwell_document_id"),
	signingUrl: text("signing_url"),
	status: text().default('pending').notNull(),
	mergeData: jsonb("merge_data").default({}).notNull(),
	sentAt: timestamp("sent_at", { withTimezone: true, mode: 'string' }),
	signedAt: timestamp("signed_at", { withTimezone: true, mode: 'string' }),
	signedByName: text("signed_by_name"),
	signedByEmail: text("signed_by_email"),
	signedPdfUrl: text("signed_pdf_url"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	createdBy: uuid("created_by"),
}, (table) => [
	index("within_retreat_agreements_lead_id_idx").using("btree", table.leadId.asc().nullsLast().op("uuid_ops")),
	index("within_retreat_agreements_package_id_idx").using("btree", table.packageId.asc().nullsLast().op("uuid_ops")),
	uniqueIndex("within_retreat_agreements_signwell_doc_id_idx").using("btree", table.signwellDocumentId.asc().nullsLast().op("text_ops")).where(sql`(signwell_document_id IS NOT NULL)`),
	foreignKey({
			columns: [table.createdBy],
			foreignColumns: [appUsers.id],
			name: "within_retreat_agreements_created_by_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.leadId],
			foreignColumns: [crmLeads.id],
			name: "within_retreat_agreements_lead_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.packageId],
			foreignColumns: [clientPackages.id],
			name: "within_retreat_agreements_package_id_fkey"
		}).onDelete("set null"),
	pgPolicy("within_retreat_agreements_admin_all", { as: "permissive", for: "all", to: ["authenticated"], using: sql`(EXISTS ( SELECT 1
   FROM app_users au
  WHERE ((au.auth_user_id = auth.uid()) AND (au.role = ANY (ARRAY['admin'::text, 'staff'::text, 'oracle'::text])))))`, withCheck: sql`(EXISTS ( SELECT 1
   FROM app_users au
  WHERE ((au.auth_user_id = auth.uid()) AND (au.role = ANY (ARRAY['admin'::text, 'staff'::text, 'oracle'::text])))))`  }),
	check("within_retreat_agreements_status_check", sql`status = ANY (ARRAY['pending'::text, 'sent'::text, 'signed'::text, 'declined'::text, 'expired'::text, 'voided'::text])`),
]);

export const crmLeads = pgTable("crm_leads", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	businessLine: text("business_line").notNull(),
	stageId: uuid("stage_id"),
	sourceId: uuid("source_id"),
	status: text().default('open'),
	lostReason: text("lost_reason"),
	firstName: text("first_name").notNull(),
	lastName: text("last_name").default("").notNull(),
	email: text(),
	phone: text(),
	city: text(),
	state: text(),
	utmSource: text("utm_source"),
	utmMedium: text("utm_medium"),
	utmCampaign: text("utm_campaign"),
	googleAdsClickId: text("google_ads_click_id"),
	metaAdsClickId: text("meta_ads_click_id"),
	patientId: uuid("patient_id"),
	contactSubmissionId: uuid("contact_submission_id"),
	estimatedValue: numeric("estimated_value").default('0'),
	actualRevenue: numeric("actual_revenue").default('0'),
	assignedTo: uuid("assigned_to"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	contactedAt: timestamp("contacted_at", { withTimezone: true, mode: 'string' }),
	convertedAt: timestamp("converted_at", { withTimezone: true, mode: 'string' }),
	closedAt: timestamp("closed_at", { withTimezone: true, mode: 'string' }),
	spaceId: uuid("space_id"),
	eventDate: date("event_date"),
	eventStartTime: text("event_start_time"),
	eventEndTime: text("event_end_time"),
	eventType: text("event_type"),
	guestCount: integer("guest_count"),
	bookingId: uuid("booking_id"),
	notes: text(),
	preferredName: text("preferred_name"),
	pronouns: text(),
	emergencyContactName: text("emergency_contact_name"),
	emergencyContactPhone: text("emergency_contact_phone"),
	emergencyContactRelationship: text("emergency_contact_relationship"),
	dietaryPreferences: text("dietary_preferences"),
	dietaryDislikes: text("dietary_dislikes"),
	roomPreferences: text("room_preferences"),
	arrivalMethod: text("arrival_method"),
	arrivalDetails: text("arrival_details"),
	arrivalPickupNeeded: boolean("arrival_pickup_needed").default(false),
	departureDetails: text("departure_details"),
	departurePickupNeeded: boolean("departure_pickup_needed").default(false),
	waiverSigned: boolean("waiver_signed").default(false),
	intakeCompleted: boolean("intake_completed").default(false),
	vendorList: text("vendor_list"),
	dayOfTimeline: text("day_of_timeline"),
	internalStaffNotes: text("internal_staff_notes"),
	depositAmount: numeric("deposit_amount"),
	depositDueAt: date("deposit_due_at"),
	depositPaidAt: timestamp("deposit_paid_at", { withTimezone: true, mode: 'string' }),
	balanceAmount: numeric("balance_amount"),
	balanceDueAt: date("balance_due_at"),
	balancePaidAt: timestamp("balance_paid_at", { withTimezone: true, mode: 'string' }),
	additionalSpaceIds: uuid("additional_space_ids").array(),
	eventEndDate: date("event_end_date"),
}, (table) => [
	index("idx_crm_leads_business_line").using("btree", table.businessLine.asc().nullsLast().op("text_ops")),
	index("idx_crm_leads_created_at").using("btree", table.createdAt.asc().nullsLast().op("timestamptz_ops")),
	index("idx_crm_leads_source_id").using("btree", table.sourceId.asc().nullsLast().op("uuid_ops")),
	index("idx_crm_leads_stage_id").using("btree", table.stageId.asc().nullsLast().op("uuid_ops")),
	index("idx_crm_leads_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.assignedTo],
			foreignColumns: [appUsers.id],
			name: "crm_leads_assigned_to_fkey"
		}),
	foreignKey({
			columns: [table.sourceId],
			foreignColumns: [crmLeadSources.id],
			name: "crm_leads_source_id_fkey"
		}),
	foreignKey({
			columns: [table.spaceId],
			foreignColumns: [spaces.id],
			name: "crm_leads_space_id_fkey"
		}),
	foreignKey({
			columns: [table.stageId],
			foreignColumns: [crmPipelineStages.id],
			name: "crm_leads_stage_id_fkey"
		}),
	pgPolicy("Authenticated users can delete leads", { as: "permissive", for: "delete", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Authenticated users can insert leads", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("Authenticated users can read leads", { as: "permissive", for: "select", to: ["authenticated"] }),
	pgPolicy("Authenticated users can update leads", { as: "permissive", for: "update", to: ["authenticated"] }),
	pgPolicy("Service role full access leads", { as: "permissive", for: "all", to: ["service_role"] }),
	check("crm_leads_status_check", sql`status = ANY (ARRAY['open'::text, 'won'::text, 'lost'::text])`),
]);

export const houseMeals = pgTable("house_meals", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	mealDate: date("meal_date").notNull(),
	startTime: time("start_time").notNull(),
	endTime: time("end_time").notNull(),
	name: text().notNull(),
	description: text(),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("house_meals_date_idx").using("btree", table.mealDate.asc().nullsLast().op("date_ops")),
	unique("house_meals_unique").on(table.mealDate, table.startTime, table.name),
	pgPolicy("house_meals_modify", { as: "permissive", for: "all", to: ["public"], using: sql`(auth.uid() IS NOT NULL)`, withCheck: sql`(auth.uid() IS NOT NULL)`  }),
	pgPolicy("house_meals_select", { as: "permissive", for: "select", to: ["public"] }),
]);

export const staffActivityTypes = pgTable("staff_activity_types", {
	staffMemberId: integer("staff_member_id").notNull(),
	activityTypeId: integer("activity_type_id").notNull(),
}, (table) => [
	foreignKey({
			columns: [table.activityTypeId],
			foreignColumns: [activityTypes.id],
			name: "staff_activity_types_activity_type_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.staffMemberId],
			foreignColumns: [staffMembers.id],
			name: "staff_activity_types_staff_member_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.staffMemberId, table.activityTypeId], name: "staff_activity_types_pkey"}),
	pgPolicy("auth_delete_staff_activity_types", { as: "permissive", for: "delete", to: ["authenticated"], using: sql`true` }),
	pgPolicy("auth_insert_staff_activity_types", { as: "permissive", for: "insert", to: ["authenticated"] }),
	pgPolicy("auth_read_staff_activity_types", { as: "permissive", for: "select", to: ["authenticated"] }),
]);

export const rolePermissions = pgTable("role_permissions", {
	role: text().notNull(),
	permissionKey: text("permission_key").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_role_permissions_role").using("btree", table.role.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.permissionKey],
			foreignColumns: [permissions.key],
			name: "role_permissions_permission_key_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.role, table.permissionKey], name: "role_permissions_pkey"}),
	pgPolicy("role_permissions_read", { as: "permissive", for: "select", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("role_permissions_write", { as: "permissive", for: "all", to: ["public"] }),
]);

export const jobTitlePermissions = pgTable("job_title_permissions", {
	jobTitleId: uuid("job_title_id").notNull(),
	permissionKey: text("permission_key").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_job_title_permissions_title").using("btree", table.jobTitleId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.jobTitleId],
			foreignColumns: [jobTitles.id],
			name: "job_title_permissions_job_title_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.permissionKey],
			foreignColumns: [permissions.key],
			name: "job_title_permissions_permission_key_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.jobTitleId, table.permissionKey], name: "job_title_permissions_pkey"}),
	pgPolicy("job_title_permissions_read", { as: "permissive", for: "select", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("job_title_permissions_write", { as: "permissive", for: "all", to: ["public"] }),
]);

export const facilitatorServices = pgTable("facilitator_services", {
	facilitatorId: uuid("facilitator_id").notNull(),
	serviceId: uuid("service_id").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("facilitator_services_service_idx").using("btree", table.serviceId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.facilitatorId],
			foreignColumns: [facilitators.id],
			name: "facilitator_services_facilitator_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.serviceId],
			foreignColumns: [services.id],
			name: "facilitator_services_service_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.facilitatorId, table.serviceId], name: "facilitator_services_pkey"}),
	pgPolicy("Authenticated users can read facilitator_services", { as: "permissive", for: "select", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Authenticated users can write facilitator_services", { as: "permissive", for: "all", to: ["authenticated"] }),
]);

export const userPermissions = pgTable("user_permissions", {
	appUserId: uuid("app_user_id").notNull(),
	permissionKey: text("permission_key").notNull(),
	granted: boolean().notNull(),
	grantedBy: uuid("granted_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_user_permissions_user").using("btree", table.appUserId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.appUserId],
			foreignColumns: [appUsers.id],
			name: "user_permissions_app_user_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.grantedBy],
			foreignColumns: [appUsers.id],
			name: "user_permissions_granted_by_fkey"
		}),
	foreignKey({
			columns: [table.permissionKey],
			foreignColumns: [permissions.key],
			name: "user_permissions_permission_key_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.appUserId, table.permissionKey], name: "user_permissions_pkey"}),
	pgPolicy("user_permissions_read", { as: "permissive", for: "select", to: ["public"], using: sql`(auth.role() = 'authenticated'::text)` }),
	pgPolicy("user_permissions_write", { as: "permissive", for: "all", to: ["public"] }),
]);

export const crmServicePackageItems = pgTable("crm_service_package_items", {
	packageId: uuid("package_id").notNull(),
	serviceId: uuid("service_id").notNull(),
	quantity: integer().default(1).notNull(),
	sortOrder: integer("sort_order").default(100).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("crm_service_package_items_service_idx").using("btree", table.serviceId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.packageId],
			foreignColumns: [crmServicePackages.id],
			name: "crm_service_package_items_package_id_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.serviceId],
			foreignColumns: [services.id],
			name: "crm_service_package_items_service_id_fkey"
		}).onDelete("cascade"),
	primaryKey({ columns: [table.packageId, table.serviceId], name: "crm_service_package_items_pkey"}),
	pgPolicy("Authenticated users can read crm_service_package_items", { as: "permissive", for: "select", to: ["authenticated"], using: sql`true` }),
	pgPolicy("Authenticated users can write crm_service_package_items", { as: "permissive", for: "all", to: ["authenticated"] }),
	check("crm_service_package_items_quantity_check", sql`quantity > 0`),
]);
